import Config

# Configure your database
repo_opts =
  case System.get_env("DATABASE_URL") do
    nil ->
      [
        username: "engram",
        password: "engram",
        hostname: "localhost",
        database: "engram_dev"
      ]

    url ->
      [url: url]
  end

config :engram,
       Engram.Repo,
       Keyword.merge(repo_opts,
         stacktrace: true,
         show_sensitive_data_on_connection_error: true,
         pool_size: 10
       )

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :engram, EngramWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "hZXoe4bVk7sJkF6CT/1jG+/4X03lcdTECjUFOWwKSlF0KAecv1CROWuFYqrtzY3k",
  # No Vite watcher here — Phoenix spawns watchers as Port children that
  # don't get cleaned up on BEAM SIGKILL, leaving orphan node processes
  # holding :5173+ across restarts. Run `make frontend-dev` separately
  # when you want hot-reload at :5173, or `bun run build` to refresh the
  # bundle Phoenix serves at :4000 / app.engram.page.
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# JWT signing secret (Joken)
config :joken, default_signer: "dev-jwt-secret-not-for-production"

# joken_jwks: use Erlang's built-in httpc adapter (hackney not in deps)
config :tesla, JokenJwks.HttpFetcher, adapter: Tesla.Adapter.Httpc

# Qdrant collection — can be overridden by QDRANT_COLLECTION env var in runtime.exs
config :engram, :qdrant_collection, "engram_notes"

# Enable dev routes for dashboard and mailbox
config :engram, dev_routes: true

# Disable SPA index.html cache so `vite build` (or `bun run build`)
# rewriting priv/static/app/index.html is picked up immediately —
# without this, Phoenix keeps serving the old asset hash and the
# browser 404s on the (now-deleted) JS file, producing a white page.
config :engram, :spa_cache_enabled?, false

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
